### ISSUE TITLE
T2_Realidad Aumentada diseno de objeto 

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-team-vo#1]
[RA_T2_Modelo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-team-vo/files/14950129/RA_T2_Modelo.pdf)

**Comment by MLR062998** [comment]
17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
